server:
 port: 8081
spring:
 # Database
 datasource:
   url: jdbc:h2:mem:authdb
   username: sa
   password: 
   driver-class-name: org.h2.Driver
 
 # JPA
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       format_sql: true
 
 # H2 Console
 h2:
   console:
     enabled: true
     path: /h2-console
# JWT
wt:
 secret: your_jwt_secret_key_here_make_it_long_and_secure_at_least_256_bits
 access-token-validity: 3600000  # 1시간
 refresh-token-validity: 604800000  # 7일
# Security
ecurity:
 permitted-urls:
   - /auth/register
   - /auth/login
   - /auth/validate
   - /h2-console/**
