server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
