server:
 port: 8081
spring:
 # Database
 datasource:
   url: jdbc:h2:mem:authdb
   username: sa
   password: 
   driver-class-name: org.h2.Driver
 
 # JPA
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       format_sql: true
 
 # H2 Console
 h2:
   console:
     enabled: true
     path: /h2-console
# Security
ecurity:
 permitted-urls:
   - /auth/register
   - /auth/login
   - /auth/validate
   - /h2-console/**
