server:
 port: 8081
spring:
 # Database
 datasource:
  url: jdbc:h2:mem:authdb
  username: sa
  password: 
  driver-class-name: org.h2.Driver
 
# JPA
jpa:
 hibernate:
  ddl-auto: update
 show-sql: true
 properties:
  hibernate:
   format_sql: true
wt:
 secret: thisIsAVeryVerySecretKeyForJwtTokenGenerationInDevelopmentEnvironment123456789
 access-token-validity: 3600000  # 1시간
 refresh-token-validity: 86400000  # 24시간
 # H2 Console
h2:
 console:
  enabled: true
   path: /h2-console
# Security
Security:
 permitted-urls:
   - /auth/register
   - /auth/login
   - /auth/validate
   - /h2-console/**
