server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/memberdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: member-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
